//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Coditate Software")]
[assembly: AssemblyCopyright("Copyright © Coditate Software 2007-2016")]
[assembly: AssemblyVersion("2016.4.18.0")]
[assembly: AssemblyFileVersion("2016.4.18.0")]
[assembly: ComVisible(false)]


